feat: enhance macOS installation script with Homebrew package management
- Changed script interpreter from sh to bash for better compatibility
- Added package and cask installation logic for macOS
- Included Homebrew installation check and package installation feedback

diff --git a/.chezmoiscripts/run_once_before_01_install-packages.sh.tmpl b/.chezmoiscripts/run_once_before_01_install-packages.sh.tmpl
--- a/.chezmoiscripts/run_once_before_01_install-packages.sh.tmpl
+++ b/.chezmoiscripts/run_once_before_01_install-packages.sh.tmpl
@@ -1,8 +1,46 @@
-#!/bin/sh
+#!/bin/bash
 {{ if eq .chezmoi.os "darwin" }}
-echo "darwin"
+echo "macos script running"
 {{ else }}
-echo "linux"
+echo "linux script running"
+{{ end }}
+
+{{ if eq .chezmoi.os "darwin" }}
+PACKAGES=(
+  exa
+  htop
+)
+CASK_PACKAGES=(
+  hiddenbar
+)
+# If Homebrew is not installed on the system, it will be installed here
+if test ! $(which brew); then
+   printf '\n\n\e[33mHomebrew not found. \e[0mInstalling Homebrew...'
+   /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
+else
+  printf '\n\n\e[0mHomebrew found. Continuing...'
+fi
+
+for package in "${PACKAGES[@]}"; do
+  if ! command -v $package &> /dev/null; then
+    printf "\n\n\e[33m$package \e[0mnot found. \e[0mInstalling..."
+    brew install $package
+  else
+    printf "\n\n\e[0m$package \e[0mfound. \e[0mContinuing..."
+  fi
+done
+
+
+printf '\n\n\e[33mInstalling cask apps...\e[0m'
+for cask in "${CASK_PACKAGES[@]}"; do
+  if ! brew list --cask $cask &> /dev/null; then
+    printf "\n\n\e[33m$cask \e[0mnot found. \e[0mInstalling..."
+    brew install --cask $cask
+  else
+    printf "\n\n\e[0m$cask \e[0mfound. \e[0mContinuing..."
+  fi
+done
+
 {{ end }}
 
 # If Oh-my-zsh is not installed on the system, it will be installed here
